server:
  port: 8080
grpc:
  server:
    port: 3000
spring:
  data:
    mongodb:
      uri: mongodb://localhost:27017/pizza_branch
      database: pizza_branch
  mvc:
    problemdetails:
      enabled: true

faker:
  enabled: false
  locale: ru
  count: 1024